language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
addons:
  sonarcloud:
    organization: xyo-network
script:
- sonar-scanner
notifications:
  slack:
    rooms:
      secure: YAtuYFURna/Noegs8/QHvZExA5ZjxkpQ9m1lB7KzdrtoTHrDmuReLwvH1FnyAp51i1LP9ld/Ql01pjT7EXMQkTaxjCfup6sCiv3I9eKwhgJ5+B40zmOrEnXG9wAe9ZirXVNBGFH8+eBpSi914vBuAkNkxrt0a96GLleODR2YoLrl+I1u2g67FSosJ8cnENva8rs0hyExwcJqRJFFc8K18UIC4qrkT4HdjYndiaPNsGtchrqJrgqU6z4fUCCn+aW5ewr3gCpp0wY/aRQelvRr68x1bcfYa796kW1+EDB6Tvj5io+MR7IlI89MLd/cvq4aA4ZFt0cwnAvGC0Z09y05VvPQCeS0XZbBVevL7iz+SoePNvwHgP0RXMKKJhUyjJPIZnPeKVWUcQNUBXpjqg6rZzk6vZugeYGhzPuoAU9u7jxpEmHZLKwKsUB6Ye//6Grwl5eLNxdjPc1+O9VzqwKfXffZX/ZGl58Ww+0R72f/95xKR1f/Z5uTMTpS10UYJ5TZ0KczCHkg+F5K6bnwacbc3Vx/wR+x7e3bp7K7COB9hEuARh/wCMMqCEtkGmMoOVQQN/7ZeO8TU0C+U7Sag7ULsi3HUXgdaankm86z5tYC3FmX7PFwGN00seW5SYHm+NQrDBgtf/87sdrbxWLo1ZTX0onVQxBvCIZ7aAHgCOssuSo=
    on_success: change # default: always
    on_failure: always # default: always
