language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
addons:
  sonarcloud:
    organization: xyo-network
notifications:
  slack:
    rooms: $SLACK_TOKEN
    on_success: change # default: always
    on_failure: always # default: always
stages:
  - name: build
  - name: test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: test
      script: sonar-scanner
    - stage: deploy 
      if: branch = master
      script: echo Hello

