version: 0.2

phases:
  build:
    commands:
      - mkdir -p "$ANDROID_HOME/licenses"
      - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
      - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
      - $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3" "platforms;android-28"
      - chmod +x ./gradlew
      - ./gradlew assemble
artifacts:
  files:
     - './app/build/outputs/apk/release/*.apk'
  discard-paths: yes